FROM docker.io/tootsuite/mastodon:v4.0.2

COPY --chown=mastodon:mastodon app /opt/mastodon/app
COPY --chown=mastodon:mastodon config /opt/mastodon/config
COPY --chown=mastodon:mastodon public /opt/mastodon/public

# Precompile assets
RUN set -e; \
    OTP_SECRET=precompile_placeholder \
    SECRET_KEY_BASE=precompile_placeholder \
    rails assets:precompile; \
    yarn cache clean; \
    find . -iname '*toothaus*' -print
