default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
toothaus-light: styles/toothaus-light.scss
toothaus-dark: styles/toothaus-dark.scss
toothaus-auto: styles/toothaus-auto.scss
